import type {
  AppSettings,
  CustomPalette,
  FontId,
  ThemeDefinition,
  ThemeId,
} from "../types";

export const themes: Record<ThemeId, ThemeDefinition> = {
  "neon-violet": {
    id: "neon-violet",
    label: "Neon Violet",
    description: "Electric violet and acid-green on tactical black",
    swatches: ["#07090e", "#121722", "#9d6cff", "#3df2b1"],
    ui: {
      app: "#07090e",
      titlebar: "#0b0e14",
      sidebar: "#0c1017",
      surface: "#0f141d",
      elevated: "#151b26",
      hover: "#1b2431",
      border: "#202a37",
      borderStrong: "#3b4b60",
      text: "#eef4fb",
      textMuted: "#8e9bad",
      textFaint: "#526174",
      accent: "#9d6cff",
      accentHover: "#b28cff",
      accentSoft: "rgba(157, 108, 255, 0.14)",
      shadow: "rgba(0, 0, 0, 0.62)",
      danger: "#ff5f78",
      warning: "#ffca4a",
      success: "#3df2b1",
    },
    xterm: {
      background: "#07090e",
      foreground: "#e8eef6",
      cursor: "#3df2b1",
      cursorAccent: "#07090e",
      selectionBackground: "#9d6cff52",
      selectionInactiveBackground: "#34405252",
      black: "#121722",
      red: "#ff5f78",
      green: "#3df2b1",
      yellow: "#ffca4a",
      blue: "#5d9dff",
      magenta: "#aa72ff",
      cyan: "#38d9ff",
      white: "#e8eef6",
      brightBlack: "#526174",
      brightRed: "#ff8094",
      brightGreen: "#6affca",
      brightYellow: "#ffdc7a",
      brightBlue: "#83b7ff",
      brightMagenta: "#c096ff",
      brightCyan: "#72e5ff",
      brightWhite: "#ffffff",
    },
  },
  "neon-cyan": {
    id: "neon-cyan",
    label: "Neon Cyan",
    description: "Cold cyan glow with acid-lime signals",
    swatches: ["#041013", "#0b2024", "#22e7f2", "#b9ff66"],
    ui: {
      app: "#041013",
      titlebar: "#061519",
      sidebar: "#07171b",
      surface: "#091c20",
      elevated: "#0d252a",
      hover: "#12343a",
      border: "#16383f",
      borderStrong: "#235d66",
      text: "#e9fdff",
      textMuted: "#8eb6ba",
      textFaint: "#567b80",
      accent: "#22e7f2",
      accentHover: "#62f5fc",
      accentSoft: "rgba(34, 231, 242, 0.14)",
      shadow: "rgba(0, 8, 10, 0.68)",
      danger: "#ff5d79",
      warning: "#ffc95b",
      success: "#b9ff66",
    },
    xterm: {
      background: "#041013",
      foreground: "#def8fa",
      cursor: "#b9ff66",
      cursorAccent: "#041013",
      selectionBackground: "#22e7f244",
      selectionInactiveBackground: "#1d626944",
      black: "#0b2024",
      red: "#ff5d79",
      green: "#b9ff66",
      yellow: "#ffc95b",
      blue: "#57a8ff",
      magenta: "#df79ff",
      cyan: "#22e7f2",
      white: "#def8fa",
      brightBlack: "#567b80",
      brightRed: "#ff8297",
      brightGreen: "#caff8e",
      brightYellow: "#ffdb83",
      brightBlue: "#7cbcff",
      brightMagenta: "#e99cff",
      brightCyan: "#67f5fc",
      brightWhite: "#ffffff",
    },
  },
  "neon-ember": {
    id: "neon-ember",
    label: "Neon Ember",
    description: "Hot coral and amber over charcoal",
    swatches: ["#120a0b", "#271316", "#ff625f", "#ffcc66"],
    ui: {
      app: "#120a0b",
      titlebar: "#180d0f",
      sidebar: "#1a0e10",
      surface: "#211113",
      elevated: "#2b171a",
      hover: "#3a1d21",
      border: "#462329",
      borderStrong: "#71404a",
      text: "#fff0ef",
      textMuted: "#c6a1a2",
      textFaint: "#86686b",
      accent: "#ff625f",
      accentHover: "#ff817e",
      accentSoft: "rgba(255, 98, 95, 0.15)",
      shadow: "rgba(10, 1, 2, 0.7)",
      danger: "#ff4d76",
      warning: "#ffcc66",
      success: "#6ff0a7",
    },
    xterm: {
      background: "#120a0b",
      foreground: "#fae8e7",
      cursor: "#ffcc66",
      cursorAccent: "#120a0b",
      selectionBackground: "#ff625f4d",
      selectionInactiveBackground: "#74383b4d",
      black: "#271316",
      red: "#ff5a76",
      green: "#6ff0a7",
      yellow: "#ffcc66",
      blue: "#6ba6ff",
      magenta: "#e779ff",
      cyan: "#51dfda",
      white: "#fae8e7",
      brightBlack: "#86686b",
      brightRed: "#ff8295",
      brightGreen: "#91f8bc",
      brightYellow: "#ffdc8c",
      brightBlue: "#91bdff",
      brightMagenta: "#ee9bff",
      brightCyan: "#7deae6",
      brightWhite: "#ffffff",
    },
  },
  midnight: {
    id: "midnight",
    label: "Midnight",
    description: "Deep blue-black with crisp cool accents",
    swatches: ["#0d1016", "#171c26", "#63a7ff", "#73daca"],
    ui: {
      app: "#0d1016",
      titlebar: "#11151c",
      sidebar: "#12161e",
      surface: "#151a23",
      elevated: "#1b222e",
      hover: "#222b39",
      border: "#272f3d",
      borderStrong: "#384357",
      text: "#e7ebf2",
      textMuted: "#98a3b5",
      textFaint: "#697486",
      accent: "#5b9fff",
      accentHover: "#75afff",
      accentSoft: "rgba(91, 159, 255, 0.16)",
      shadow: "rgba(0, 0, 0, 0.42)",
      danger: "#ff6b70",
      warning: "#f5bd62",
      success: "#65d28b",
    },
    xterm: {
      background: "#0d1016",
      foreground: "#dce2ec",
      cursor: "#7eb4ff",
      cursorAccent: "#0d1016",
      selectionBackground: "#31578399",
      selectionInactiveBackground: "#273c5599",
      black: "#171c26",
      red: "#ff6b70",
      green: "#65d28b",
      yellow: "#f5bd62",
      blue: "#63a7ff",
      magenta: "#c792ea",
      cyan: "#73daca",
      white: "#dce2ec",
      brightBlack: "#697486",
      brightRed: "#ff8589",
      brightGreen: "#7ee2a1",
      brightYellow: "#ffd07b",
      brightBlue: "#82b9ff",
      brightMagenta: "#d5a6f3",
      brightCyan: "#8ce5d9",
      brightWhite: "#ffffff",
    },
  },
  graphite: {
    id: "graphite",
    label: "Graphite",
    description: "Neutral macOS graphite with subtle contrast",
    swatches: ["#171719", "#252528", "#a8b0bd", "#72c78c"],
    ui: {
      app: "#171719",
      titlebar: "#1b1b1e",
      sidebar: "#1d1d20",
      surface: "#202023",
      elevated: "#29292d",
      hover: "#323237",
      border: "#35353a",
      borderStrong: "#4a4a51",
      text: "#efeff1",
      textMuted: "#a2a2aa",
      textFaint: "#707078",
      accent: "#9ea8b7",
      accentHover: "#b4bcc8",
      accentSoft: "rgba(174, 184, 199, 0.14)",
      shadow: "rgba(0, 0, 0, 0.46)",
      danger: "#ff6961",
      warning: "#efbf65",
      success: "#70c98a",
    },
    xterm: {
      background: "#171719",
      foreground: "#e7e7e9",
      cursor: "#c6c6ca",
      cursorAccent: "#171719",
      selectionBackground: "#55555f88",
      black: "#252528",
      red: "#ff6961",
      green: "#70c98a",
      yellow: "#efbf65",
      blue: "#9eacbf",
      magenta: "#c2a3c7",
      cyan: "#8bc4c0",
      white: "#dadadd",
      brightBlack: "#73737b",
      brightRed: "#ff8882",
      brightGreen: "#8bd7a0",
      brightYellow: "#f7cf84",
      brightBlue: "#b4c0cf",
      brightMagenta: "#d2b8d6",
      brightCyan: "#a4d4d0",
      brightWhite: "#ffffff",
    },
  },
  daylight: {
    id: "daylight",
    label: "Daylight",
    description: "Warm paper surfaces for bright environments",
    swatches: ["#f4f1e9", "#ffffff", "#1672b8", "#398b55"],
    ui: {
      app: "#ebe8e0",
      titlebar: "#f4f1e9",
      sidebar: "#f6f3ec",
      surface: "#fbfaf6",
      elevated: "#ffffff",
      hover: "#e9e5dc",
      border: "#d6d1c7",
      borderStrong: "#bbb5aa",
      text: "#292c32",
      textMuted: "#656a73",
      textFaint: "#92969d",
      accent: "#1672b8",
      accentHover: "#0a83d2",
      accentSoft: "rgba(22, 114, 184, 0.13)",
      shadow: "rgba(58, 47, 30, 0.2)",
      danger: "#c43d48",
      warning: "#a46d12",
      success: "#398b55",
    },
    xterm: {
      background: "#fbfaf6",
      foreground: "#292c32",
      cursor: "#1672b8",
      cursorAccent: "#fbfaf6",
      selectionBackground: "#91c8ee88",
      black: "#333740",
      red: "#c43d48",
      green: "#398b55",
      yellow: "#a46d12",
      blue: "#1672b8",
      magenta: "#84539b",
      cyan: "#247f84",
      white: "#e1ddd4",
      brightBlack: "#747983",
      brightRed: "#db5862",
      brightGreen: "#4ca367",
      brightYellow: "#bb8529",
      brightBlue: "#2589cf",
      brightMagenta: "#9a6bb0",
      brightCyan: "#39969b",
      brightWhite: "#ffffff",
    },
  },
  ocean: {
    id: "ocean",
    label: "Ocean",
    description: "Inky teal with sea-glass highlights",
    swatches: ["#071519", "#10262c", "#36b5b8", "#9bd36a"],
    ui: {
      app: "#071519",
      titlebar: "#0a1b20",
      sidebar: "#0b1d22",
      surface: "#0d2228",
      elevated: "#122b32",
      hover: "#18363e",
      border: "#1b3941",
      borderStrong: "#2c5660",
      text: "#e4f0ef",
      textMuted: "#8da9aa",
      textFaint: "#5e7d80",
      accent: "#36b5b8",
      accentHover: "#4ac8ca",
      accentSoft: "rgba(54, 181, 184, 0.15)",
      shadow: "rgba(0, 8, 10, 0.5)",
      danger: "#ff7474",
      warning: "#e6bc68",
      success: "#8acb72",
    },
    xterm: {
      background: "#071519",
      foreground: "#dbe9e8",
      cursor: "#52c9ca",
      cursorAccent: "#071519",
      selectionBackground: "#24626999",
      black: "#10262c",
      red: "#ff7474",
      green: "#8acb72",
      yellow: "#e6bc68",
      blue: "#57a9d8",
      magenta: "#c68ed5",
      cyan: "#36b5b8",
      white: "#dbe9e8",
      brightBlack: "#5e7d80",
      brightRed: "#ff9191",
      brightGreen: "#a1dc8d",
      brightYellow: "#f2cd83",
      brightBlue: "#75bce5",
      brightMagenta: "#d8a7e2",
      brightCyan: "#55c9cb",
      brightWhite: "#ffffff",
    },
  },
  matrix: {
    id: "matrix",
    label: "Matrix",
    description: "Near-black tactical UI with phosphor-green signals",
    swatches: ["#030805", "#0b1710", "#54f58c", "#d7ff63"],
    ui: {
      app: "#030805",
      titlebar: "#060c08",
      sidebar: "#07100b",
      surface: "#09140d",
      elevated: "#0d1b12",
      hover: "#13271a",
      border: "#173321",
      borderStrong: "#28603b",
      text: "#e5f8e9",
      textMuted: "#85a98e",
      textFaint: "#4d7056",
      accent: "#54f58c",
      accentHover: "#78ffa6",
      accentSoft: "rgba(84, 245, 140, 0.13)",
      shadow: "rgba(0, 5, 1, 0.72)",
      danger: "#ff5f70",
      warning: "#d7ff63",
      success: "#54f58c",
    },
    xterm: {
      background: "#030805",
      foreground: "#ccebd3",
      cursor: "#d7ff63",
      cursorAccent: "#030805",
      selectionBackground: "#2f784b88",
      black: "#0b1710",
      red: "#ff5f70",
      green: "#54f58c",
      yellow: "#d7ff63",
      blue: "#60a5fa",
      magenta: "#c084fc",
      cyan: "#45e8c2",
      white: "#ccebd3",
      brightBlack: "#4d7056",
      brightRed: "#ff8290",
      brightGreen: "#80ffaa",
      brightYellow: "#e6ff91",
      brightBlue: "#87bcff",
      brightMagenta: "#d2a4ff",
      brightCyan: "#78f5d8",
      brightWhite: "#f4fff7",
    },
  },
  "tokyo-night": {
    id: "tokyo-night",
    label: "Tokyo Night",
    description: "Indigo night surfaces with electric blue and magenta",
    swatches: ["#0f111a", "#1a1b2e", "#7aa2f7", "#bb9af7"],
    ui: {
      app: "#0f111a",
      titlebar: "#131521",
      sidebar: "#151724",
      surface: "#171925",
      elevated: "#1f2335",
      hover: "#292e42",
      border: "#292e42",
      borderStrong: "#3b4261",
      text: "#c0caf5",
      textMuted: "#9aa5ce",
      textFaint: "#565f89",
      accent: "#7aa2f7",
      accentHover: "#9ab8ff",
      accentSoft: "rgba(122, 162, 247, 0.15)",
      shadow: "rgba(3, 4, 12, 0.64)",
      danger: "#f7768e",
      warning: "#e0af68",
      success: "#9ece6a",
    },
    xterm: {
      background: "#0f111a",
      foreground: "#c0caf5",
      cursor: "#c0caf5",
      cursorAccent: "#0f111a",
      selectionBackground: "#33467c99",
      black: "#1a1b26",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#a9b1d6",
      brightBlack: "#565f89",
      brightRed: "#ff899d",
      brightGreen: "#b9e88b",
      brightYellow: "#f2c681",
      brightBlue: "#9ab8ff",
      brightMagenta: "#cdb2ff",
      brightCyan: "#9de0ff",
      brightWhite: "#d7dcff",
    },
  },
  gruvbox: {
    id: "gruvbox",
    label: "Gruvbox",
    description: "Warm retro contrast with strong semantic ANSI colors",
    swatches: ["#1d2021", "#3c3836", "#fabd2f", "#b8bb26"],
    ui: {
      app: "#1d2021",
      titlebar: "#242424",
      sidebar: "#282828",
      surface: "#2b2928",
      elevated: "#3c3836",
      hover: "#504945",
      border: "#4a443f",
      borderStrong: "#665c54",
      text: "#ebdbb2",
      textMuted: "#bdae93",
      textFaint: "#7c6f64",
      accent: "#fabd2f",
      accentHover: "#ffd05c",
      accentSoft: "rgba(250, 189, 47, 0.13)",
      shadow: "rgba(16, 12, 9, 0.58)",
      danger: "#fb4934",
      warning: "#fabd2f",
      success: "#b8bb26",
    },
    xterm: {
      background: "#1d2021",
      foreground: "#ebdbb2",
      cursor: "#fe8019",
      cursorAccent: "#1d2021",
      selectionBackground: "#665c5488",
      black: "#282828",
      red: "#cc241d",
      green: "#98971a",
      yellow: "#d79921",
      blue: "#458588",
      magenta: "#b16286",
      cyan: "#689d6a",
      white: "#a89984",
      brightBlack: "#928374",
      brightRed: "#fb4934",
      brightGreen: "#b8bb26",
      brightYellow: "#fabd2f",
      brightBlue: "#83a598",
      brightMagenta: "#d3869b",
      brightCyan: "#8ec07c",
      brightWhite: "#ebdbb2",
    },
  },
  "rose-pine": {
    id: "rose-pine",
    label: "Rosé Pine",
    description: "Muted ink, rose highlights, and balanced pastel ANSI",
    swatches: ["#191724", "#26233a", "#ebbcba", "#9ccfd8"],
    ui: {
      app: "#191724",
      titlebar: "#1f1d2e",
      sidebar: "#211f32",
      surface: "#26233a",
      elevated: "#2a273f",
      hover: "#393552",
      border: "#393552",
      borderStrong: "#524f67",
      text: "#e0def4",
      textMuted: "#908caa",
      textFaint: "#6e6a86",
      accent: "#c4a7e7",
      accentHover: "#d6baff",
      accentSoft: "rgba(196, 167, 231, 0.15)",
      shadow: "rgba(11, 9, 18, 0.58)",
      danger: "#eb6f92",
      warning: "#f6c177",
      success: "#9ccfd8",
    },
    xterm: {
      background: "#191724",
      foreground: "#e0def4",
      cursor: "#ebbcba",
      cursorAccent: "#191724",
      selectionBackground: "#524f6788",
      black: "#26233a",
      red: "#eb6f92",
      green: "#9ccfd8",
      yellow: "#f6c177",
      blue: "#31748f",
      magenta: "#c4a7e7",
      cyan: "#9ccfd8",
      white: "#e0def4",
      brightBlack: "#6e6a86",
      brightRed: "#f08aaa",
      brightGreen: "#b1e0e7",
      brightYellow: "#ffd394",
      brightBlue: "#4f91ad",
      brightMagenta: "#d5b8f2",
      brightCyan: "#b6e6ed",
      brightWhite: "#f4f1ff",
    },
  },
};

export const fonts: Record<FontId, { label: string; css: string }> = {
  cascadia: {
    label: "Cascadia Code",
    css: '"Cascadia Code", "Noto Color Emoji", "Segoe UI Emoji", "Apple Color Emoji", monospace',
  },
  "ibm-plex": {
    label: "IBM Plex Mono",
    css: '"IBM Plex Mono", "Noto Color Emoji", "Segoe UI Emoji", "Apple Color Emoji", monospace',
  },
  "dm-mono": {
    label: "DM Mono",
    css: '"DM Mono", "Noto Color Emoji", "Segoe UI Emoji", "Apple Color Emoji", monospace',
  },
};

export function paletteFromTheme(theme: ThemeDefinition): CustomPalette {
  return {
    app: theme.ui.app,
    titlebar: theme.ui.titlebar,
    sidebar: theme.ui.sidebar,
    surface: theme.ui.surface,
    elevated: theme.ui.elevated,
    hover: theme.ui.hover,
    border: theme.ui.border,
    borderStrong: theme.ui.borderStrong,
    text: theme.ui.text,
    textMuted: theme.ui.textMuted,
    textFaint: theme.ui.textFaint,
    accent: theme.ui.accent,
    accentHover: theme.ui.accentHover,
    danger: theme.ui.danger,
    warning: theme.ui.warning,
    success: theme.ui.success,
    terminalBackground: theme.xterm.background ?? theme.ui.app,
    terminalForeground: theme.xterm.foreground ?? theme.ui.text,
    terminalCursor: theme.xterm.cursor ?? theme.ui.accent,
    terminalSelection:
      normalizeHex(theme.xterm.selectionBackground) ?? theme.ui.accent,
    ansiBlack: theme.xterm.black ?? theme.ui.app,
    ansiRed: theme.xterm.red ?? theme.ui.danger,
    ansiGreen: theme.xterm.green ?? theme.ui.success,
    ansiYellow: theme.xterm.yellow ?? theme.ui.warning,
    ansiBlue: theme.xterm.blue ?? theme.ui.accent,
    ansiMagenta: theme.xterm.magenta ?? theme.ui.accent,
    ansiCyan: theme.xterm.cyan ?? theme.ui.accent,
    ansiWhite: theme.xterm.white ?? theme.ui.text,
  };
}

export function resolveTheme(
  appearance: AppSettings["appearance"],
): ThemeDefinition {
  const base = themes[appearance.theme];
  const palette = appearance.advancedColors
    ? appearance.customPalette
    : paletteFromTheme(base);
  const improveContrast = appearance.highContrastText
    ? 0.58
    : appearance.advancedColors
      ? 0
      : 0.3;
  const textMuted = mixColors(
    palette.textMuted,
    palette.text,
    improveContrast,
  );
  const textFaint = mixColors(
    palette.textFaint,
    palette.text,
    appearance.highContrastText
      ? 0.68
      : appearance.advancedColors
        ? 0
        : 0.45,
  );

  return {
    ...base,
    ui: {
      app: palette.app,
      titlebar: palette.titlebar,
      sidebar: palette.sidebar,
      surface: palette.surface,
      elevated: palette.elevated,
      hover: palette.hover,
      border: palette.border,
      borderStrong: palette.borderStrong,
      text: palette.text,
      textMuted,
      textFaint,
      accent: palette.accent,
      accentHover: palette.accentHover,
      accentSoft: withAlpha(palette.accent, 0.16),
      shadow: withAlpha(palette.ansiBlack, 0.58),
      danger: palette.danger,
      warning: palette.warning,
      success: palette.success,
    },
    xterm: {
      ...base.xterm,
      background: withAlpha(
        palette.terminalBackground,
        appearance.opacity,
      ),
      foreground: palette.terminalForeground,
      cursor: palette.terminalCursor,
      cursorAccent: palette.terminalBackground,
      selectionBackground: withAlpha(palette.terminalSelection, 0.46),
      selectionInactiveBackground: withAlpha(
        palette.terminalSelection,
        0.25,
      ),
      black: palette.ansiBlack,
      red: palette.ansiRed,
      green: palette.ansiGreen,
      yellow: palette.ansiYellow,
      blue: palette.ansiBlue,
      magenta: palette.ansiMagenta,
      cyan: palette.ansiCyan,
      white: palette.ansiWhite,
      brightBlack: mixColors(palette.ansiBlack, palette.ansiWhite, 0.42),
      brightRed: mixColors(palette.ansiRed, "#ffffff", 0.22),
      brightGreen: mixColors(palette.ansiGreen, "#ffffff", 0.22),
      brightYellow: mixColors(palette.ansiYellow, "#ffffff", 0.2),
      brightBlue: mixColors(palette.ansiBlue, "#ffffff", 0.22),
      brightMagenta: mixColors(palette.ansiMagenta, "#ffffff", 0.22),
      brightCyan: mixColors(palette.ansiCyan, "#ffffff", 0.22),
      brightWhite: mixColors(palette.ansiWhite, "#ffffff", 0.38),
    },
  };
}

export function applyTheme(
  theme: ThemeDefinition,
  appearance: AppSettings["appearance"],
) {
  const root = document.documentElement;
  for (const [name, value] of Object.entries(theme.ui)) {
    root.style.setProperty(`--${toKebabCase(name)}`, value);
  }
  root.style.setProperty(
    "--ui-font-family",
    buildFontStack(appearance.uiFontFamily, false),
  );
  root.style.setProperty(
    "--terminal-font-family",
    buildFontStack(appearance.terminalFontFamily, true),
  );
  root.style.setProperty("--ui-font-size", `${appearance.uiFontSize}px`);
  root.style.setProperty("--ui-radius", `${appearance.cornerRadius}px`);
  root.style.setProperty("--panel-gap", `${appearance.panelGap}px`);
  root.style.setProperty("--interface-blur", `${appearance.interfaceBlur}px`);
  root.style.setProperty(
    "--window-opacity",
    String(Math.min(1, Math.max(0.2, appearance.interfaceOpacity))),
  );
  root.dataset.theme = theme.id;
  root.dataset.backgroundGrid = String(appearance.showBackgroundGrid);
  root.dataset.highContrast = String(appearance.highContrastText);
}

function toKebabCase(value: string) {
  return value.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

export function buildFontStack(family: string, monospace: boolean) {
  const clean = family.replace(/["'`;{}]/g, "").trim().slice(0, 128);
  const primary =
    !clean || clean === "system-ui"
      ? "system-ui"
      : `"${clean.replaceAll("\\", "\\\\")}"`;
  return [
    primary,
    '"Noto Color Emoji"',
    '"Segoe UI Emoji"',
    '"Apple Color Emoji"',
    monospace ? "monospace" : "sans-serif",
  ].join(", ");
}

function normalizeHex(value: string | undefined) {
  if (!value) return null;
  const match = value.match(/^#([\da-f]{6})/i);
  return match ? `#${match[1]}` : null;
}

function withAlpha(value: string, alpha: number) {
  const hex = normalizeHex(value);
  if (!hex) return value;
  if (alpha >= 0.999) return hex;
  const channels = [1, 3, 5].map((offset) =>
    Number.parseInt(hex.slice(offset, offset + 2), 16),
  );
  return `rgba(${channels.join(", ")}, ${Math.min(1, Math.max(0, alpha))})`;
}

function mixColors(from: string, to: string, ratio: number) {
  const left = normalizeHex(from);
  const right = normalizeHex(to);
  if (!left || !right || ratio <= 0) return from;
  const read = (value: string) =>
    [1, 3, 5].map((offset) =>
      Number.parseInt(value.slice(offset, offset + 2), 16),
    );
  const start = read(left);
  const end = read(right);
  return `#${start
    .map((value, index) =>
      Math.round(value + (end[index] - value) * Math.min(1, ratio))
        .toString(16)
        .padStart(2, "0"),
    )
    .join("")}`;
}
